### ISSUE TITLE
Error when trying to use layers

### ISSUE THREAD

**Issue by appym005** [PattyHoswell/Visibility-Collision-Shape-Editor#3]
Invalid access to property or key '_visibility_eip' on a base object of type 'EditorPlugin (VisibilityCollisionShapeEP)'.

This error shows when click on the visibility layers option under the Collision Visibility menu.

**Comment by PattyHoswell** [comment]
Thank you for reporting this, i made a rename of the variable a while ago and forgot to rename the variable using it!

**Comment by PattyHoswell** [comment]
Commit 25ed37f should fix this issue.
